const IG_S = 'https://www.instagram.com/eycrstudio'
const IG_A = 'https://www.instagram.com/eycraircond'

export const BIZ = {
  name: 'EY Creative Reno & Designs',
  short: 'EYCR',
  phone: '+60 10-233 0434',
  tel: '+60102330434',
  wa: '60102330434',
  email: 'eycr.designs@gmail.com',
  street: 'Jalan Seri Wangsa 2, Wangsa Maju',
  city: '53300 Kuala Lumpur',
  maps: 'https://www.google.com/maps/place/EY+Creative+Reno+%26+Designs/@3.194511,101.7375491,17z',
  directions: 'https://www.google.com/maps/dir/?api=1&destination=3.194511,101.737549',
  rating: '4.8',
  reviews: 17,
  linktree: 'https://linktr.ee/eycr',
  social: {
    studio: [['Instagram', IG_S], ['Facebook', 'https://www.facebook.com/eycrstudio'], ['TikTok', 'https://www.tiktok.com/@eycrstudio']],
    aircond: [['Instagram', IG_A], ['Facebook', 'https://www.facebook.com/profile.php?id=61583128417339'], ['TikTok', 'https://www.tiktok.com/@eycraircond']],
  } as Record<'studio' | 'aircond', [string, string][]>,
  igStudio: IG_S,
  igAircond: IG_A,
}

/** Project photos and links come from EYCR's public Instagram posts. */
export const PROJECTS = [
  { img: 'p-wangsamas', date: '2026-09-20', href: `${IG_S}/p/DdiOPQBmhQd/` },
  { img: 'p-pocket', date: '2026-07-27', href: `${IG_S}/p/DbUfPjrGmgj/` },
  { img: 'p-blue', date: '2026-06-15', href: `${IG_S}/p/DZoWnlMGi72/` },
  { img: 'p-living', date: '2026-05-17', href: `${IG_S}/p/DYdsjr7Go-4/` },
  { img: 'p-fluted', date: '2026-04-01', href: `${IG_S}/p/DWnPUIOGtPU/` },
  { img: 'p-curve', date: '2026-03-29', href: `${IG_S}/p/DWfkGceD2UB/` },
  { img: 'p-bedroom', date: '2026-03-28', href: `${IG_S}/p/DWbAcQmGjtO/` },
  { img: 'p-door', date: '2026-03-26', href: `${IG_S}/reel/DWX59SYj8KT/` },
  { img: 'p-green', date: '2026-03-12', href: `${IG_S}/p/DV0KAvYD-QV/` },
]
export const JOBS = [
  { img: 'a-install', date: '2026-09-18', href: `${IG_A}/p/Ddc6KjlE1BH/` },
  { img: 'a-truck', date: '2026-09-18', href: `${IG_A}/reel/DdbBeqOBIMN/` },
  { img: 'a-ladder', date: '2026-08-07', href: `${IG_A}/reel/DbuuDfzhm2r/` },
  { img: 'a-service', date: '2026-07-07', href: `${IG_A}/reel/DahUz98BR8z/` },
]

const en = {
  meta: {
    title: 'EY Creative Reno & Designs (EYCR) | Renovation, Interior Design, Aircond & Electrical, Wangsa Maju KL',
    desc: 'EYCR in Wangsa Maju, Kuala Lumpur: kitchen and bathroom renovation, interior design and custom cabinets, plus aircond servicing, installation and wiring. 4.8 on Google. Free consultation and quote.',
  },
  langLabel: 'BM',
  langAria: 'BM · Tukar ke Bahasa Melayu',
  a11y: { skip: 'Skip to content', main: 'Main', mobile: 'Mobile menu', menuOpen: 'Open menu', menuClose: 'Close menu', bar: 'Quick contact', close: 'Close', prev: 'Previous project', next: 'Next project', home: 'EY Creative Reno & Designs, home' },
  nav: [['work', 'Projects'], ['services', 'Services'], ['about', 'About'], ['reviews', 'Reviews'], ['contact', 'Contact']] as [string, string][],
  status: { open: 'Open now', closes: 'until 6 pm', closed: 'Closed', opensToday: 'opens 9 am', opensTomorrow: 'opens 9 am tomorrow', opensMon: 'opens Mon 9 am' },
  waCta: 'WhatsApp',
  call: 'Call',
  hero: {
    kicker: 'Wangsa Maju, Kuala Lumpur',
    h1: 'Renovation, interior design, aircond and electrical work.',
    sub: 'We’re EYCR. Our studio designs and builds kitchens, bathrooms and built-ins. Our aircond and electrical team services, installs and repairs units and handles wiring.',
    cta: 'Free consultation & quote',
    cta2: 'See our projects',
    reviewsWord: 'Google reviews',
    hoursVal: '9 am–6 pm',
    hours: 'Mon–Sat',
    teamsVal: '2 teams',
    teams: 'Studio · Aircond',
    caps: ['Kitchen, Villa Wangsamas', 'Shower bathroom', 'Aircond servicing'],
    credit: 'Photos: EYCR on Instagram',
  },
  work: {
    kicker: 'Projects',
    title: 'Recent projects',
    sub: 'Kitchens, bathrooms, living rooms and bedrooms by EYCR Studio, as posted on our Instagram.',
    open: 'View project',
    posted: 'Posted',
    ig: 'View the post on Instagram',
    credit: 'Photo: EYCR Studio on Instagram',
    more: 'More projects on Instagram',
    items: [
      { kind: 'Kitchen', title: 'Kitchen at Villa Wangsamas', text: 'A simple, earthy palette of muted tones and natural textures. Yellow grout adds a quiet touch of contrast without taking over.' },
      { kind: 'Kitchen', title: 'Full kitchen with a pocket door', text: 'Custom cabinets and the ceiling, all by EYCR Studio. The client asked for a pocket door to hide the appliances, and an undermount sink with a double-layer worktop.' },
      { kind: 'Kitchen', title: 'All-blue kitchen', text: 'A full kitchen renovation with custom cabinets in blue.' },
      { kind: 'Living room', title: 'Minimal living room', text: 'Textured finishes, ambient lighting and clean joins around the TV wall.' },
      { kind: 'Living room', title: 'Fluted-panel TV wall', text: 'Fluted panels with a soft concealed light frame the living area and give a minimal room some depth.' },
      { kind: 'Bathroom', title: 'Green and blue bathroom', text: 'Green and blue feature tiles with curved edges, set against white 2×2 wall and floor tiles.' },
      { kind: 'Bedroom', title: 'Bedroom built-ins', text: 'A fluted-panel vanity with ambient lighting, custom wardrobes and a matching bedhead, in warm tones.' },
      { kind: 'Carpentry', title: 'The “magic door”', text: 'A sliding door on a concealed track with no floor rail, so it seems to float along the wall.' },
      { kind: 'Bathroom', title: 'Deep-green shower', text: 'Deep green tiles in the shower against neutral walls and a terrazzo floor, with a lit niche, a frosted window and matte black fittings.' },
    ],
  },
  services: {
    kicker: 'Services',
    title: 'What we do',
    free: 'Design consultation and quotation are free.',
    follow: 'Follow',
    teams: [
      { id: 'studio' as const, name: 'EYCR Studio', role: 'Interior design & renovation', text: 'From one bathroom to a whole home: layout, custom cabinets and wardrobes, ceilings, lighting, tiling and painting.', list: ['Interior design', 'Kitchen renovation', 'Bathroom renovation', 'Custom cabinets & wardrobes', 'Ceilings & lighting', 'Tiling & painting'] },
      { id: 'aircond' as const, name: 'EYCR Aircond & Electrical', role: 'Air-conditioning & wiring', text: 'Clean, professional work at a fair price, for homes and offices. Our technicians have more than 8 years of experience.', list: ['Aircond servicing', 'Installation & dismantling', 'Troubleshooting', 'Repairs', 'Electrical & wiring'] },
    ],
    jobsTitle: 'Recent aircond & electrical jobs',
    jobs: [
      'Dismantled and installed two 1HP inverter units, with a new drain pipe, new wiring and new flare nuts.',
      'Serviced more than 20 aircond units in one job.',
      'Aircond and copper pipe replacement at Villa Wangsamas.',
      'Servicing five air-conditioner units.',
    ],
    jobsCredit: 'Photos: EYCR Aircond on Instagram',
    tip: 'Our tip: service each unit every 3–6 months, clean the filter regularly and keep the outdoor unit clear.',
  },
  about: {
    kicker: 'About',
    title: 'About EYCR',
    paras: [
      'EY Creative Reno & Designs, or EYCR, is a renovation and services company in Wangsa Maju, Kuala Lumpur.',
      'We work as two teams. EYCR Studio handles interior design and renovation: kitchens, bathrooms, living rooms, bedrooms and custom carpentry. EYCR Aircond & Electrical services, installs and repairs air-conditioners and takes on wiring work.',
      'Many recent jobs are close to the office, including kitchen and aircond work at Villa Wangsamas.',
    ],
    facts: [['Company', 'EY Creative Reno & Designs (EYCR)'], ['Based in', 'Wangsa Maju, Kuala Lumpur'], ['Hours', 'Mon–Sat, 9 am–6 pm'], ['Google rating', '4.8 from 17 reviews']] as [string, string][],
    stepsTitle: 'Getting a quote',
    steps: [
      ['WhatsApp us', 'Send a few photos of the space or the aircond unit, and your location.'],
      ['Consultation & quote', 'Design consultation and quotation are free.'],
      ['We get to work', 'Once you’re happy with the quotation, we schedule the job.'],
    ] as [string, string][],
  },
  reviews: {
    kicker: 'Reviews',
    title: 'What customers say',
    sub: '4.8 from 17 Google reviews',
    all: 'Read all reviews on Google',
    source: 'Google review',
    prev: 'Previous review',
    next: 'Next review',
    region: 'Customer reviews, swipe for more',
    origNote: '',
    items: [
      { tag: 'Electrical', date: '2026-02-04', text: 'Excellent service as always. Had to call for wiring issue as urgent matter today and their staff dealt with it swiftly and professionally. Job well done.' },
      { tag: 'Aircond', date: '2026-01-06', text: 'Excellent air-conditioning service. The staff were friendly and explained the issue clearly before starting the work. Service was fast and neat, and the air-cond is much colder after servicing.' },
      { tag: 'Renovation', date: '2023-10-26', text: 'I really can’t say enough good things about this company … This was a 1-month renovation and it was right on schedule, start to finish.' },
      { tag: 'Service', date: '2026-01-07', text: 'Good customer service, … punctual, and cleans the area after work.' },
      { tag: 'Aircond + electrical', date: '2022-12-29', text: 'Highly recommended. Reliable. Friendly … showed up on time, friendly, patient, clean and most of all sincere.' },
    ],
  },
  faq: {
    kicker: 'FAQ',
    title: 'Common questions',
    items: [
      ['Is the consultation really free?', 'Yes. Design consultation and quotation are free. WhatsApp us a few photos and your location to start.'],
      ['Which areas do you cover?', 'We’re based in Wangsa Maju, Kuala Lumpur. Send your location on WhatsApp and we’ll confirm whether we can come to you.'],
      ['How often should my aircond be serviced?', 'Every 3 to 6 months. Clean the filter regularly in between and keep the outdoor unit clear so it can breathe.'],
      ['What should I send for an aircond problem?', 'A photo of the indoor unit and its label (brand and model), what’s happening (not cold, leaking, noisy), how many units, and roughly when it was last serviced.'],
      ['The power keeps tripping. What should I do?', 'If you notice a burning smell, sparks or smoke, switch off the main switch at the DB box, keep clear and call us. For tripping or a partial power cut, WhatsApp a photo of the DB box and tell us what was switched on when it tripped.'],
    ] as [string, string][],
  },
  contact: {
    kicker: 'Contact',
    title: 'Talk to us',
    sub: 'WhatsApp is quickest. Send a few photos and your location, and we’ll reply during working hours.',
    phone: 'Phone & WhatsApp',
    email: 'Email',
    address: 'Address',
    hours: 'Hours',
    days: [['Mon–Sat', '9 am – 6 pm'], ['Sunday', 'Closed']] as [string, string][],
    today: 'Today',
    maps: 'Open in Google Maps',
    directions: 'Get directions',
    follow: 'Follow us',
    links: 'All links',
    mapAlt: 'Map of Wangsa Maju showing the EYCR location near Jalan Seri Wangsa',
    mapCredit: 'Map © OpenStreetMap contributors',
    waMsg: 'Hi EYCR, I’d like to ask about a job.',
    waQuote: 'Hi EYCR, I’d like a free consultation and quote.',
  },
  footer: {
    blurb: 'Interior design, renovation, aircond and electrical work in Wangsa Maju, Kuala Lumpur.',
    explore: 'Explore',
    reach: 'Contact',
    photos: 'Photos: @eycrstudio and @eycraircond on Instagram.',
    rights: 'All rights reserved.',
    pitch: 'Website concept prepared for this studio. Not an official site yet — open to making it yours.',
    pitchLink: 'Talk to the designer',
  },
}

export type Content = typeof en

const ms: Content = {
  meta: {
    title: 'EY Creative Reno & Designs (EYCR) | Renovasi, Reka Bentuk Dalaman, Aircond & Elektrik, Wangsa Maju KL',
    desc: 'EYCR di Wangsa Maju, Kuala Lumpur: renovasi dapur dan bilik air, reka bentuk dalaman dan kabinet tempahan, serta servis, pasang aircond dan pendawaian. 4.8 di Google. Konsultasi dan sebut harga percuma.',
  },
  langLabel: 'EN',
  langAria: 'EN · Switch to English',
  a11y: { skip: 'Langkau ke kandungan', main: 'Utama', mobile: 'Menu mudah alih', menuOpen: 'Buka menu', menuClose: 'Tutup menu', bar: 'Hubungi pantas', close: 'Tutup', prev: 'Projek sebelumnya', next: 'Projek seterusnya', home: 'EY Creative Reno & Designs, laman utama' },
  nav: [['work', 'Projek'], ['services', 'Servis'], ['about', 'Tentang kami'], ['reviews', 'Ulasan'], ['contact', 'Hubungi']],
  status: { open: 'Buka sekarang', closes: 'hingga 6 ptg', closed: 'Tutup', opensToday: 'buka 9 pagi', opensTomorrow: 'buka esok 9 pagi', opensMon: 'buka Isnin 9 pagi' },
  waCta: 'WhatsApp',
  call: 'Telefon',
  hero: {
    kicker: 'Wangsa Maju, Kuala Lumpur',
    h1: 'Renovasi, reka bentuk dalaman, aircond dan kerja elektrik.',
    sub: 'Kami EYCR. Studio kami mereka dan membina dapur, bilik air dan kabinet. Pasukan aircond dan elektrik kami pula buat servis, pemasangan, baiki unit dan kerja pendawaian.',
    cta: 'Konsultasi & sebut harga percuma',
    cta2: 'Lihat projek kami',
    reviewsWord: 'ulasan Google',
    hoursVal: '9 pg–6 ptg',
    hours: 'Isnin–Sabtu',
    teamsVal: '2 pasukan',
    teams: 'Studio · Aircond',
    caps: ['Dapur, Villa Wangsamas', 'Bilik air', 'Servis aircond'],
    credit: 'Foto: EYCR di Instagram',
  },
  work: {
    kicker: 'Projek',
    title: 'Projek terkini',
    sub: 'Dapur, bilik air, ruang tamu dan bilik tidur oleh EYCR Studio, seperti yang dikongsi di Instagram kami.',
    open: 'Lihat projek',
    posted: 'Dikongsi',
    ig: 'Lihat hantaran di Instagram',
    credit: 'Foto: EYCR Studio di Instagram',
    more: 'Lebih banyak projek di Instagram',
    items: [
      { kind: 'Dapur', title: 'Dapur di Villa Wangsamas', text: 'Palet ringkas bertona tanah, dengan warna lembut dan tekstur semula jadi. Grout kuning memberi sedikit kontras tanpa terlalu menonjol.' },
      { kind: 'Dapur', title: 'Dapur penuh dengan pintu poket', text: 'Kabinet tempahan dan siling, semuanya oleh EYCR Studio. Pelanggan minta pintu poket untuk menyorok peralatan dapur, dan sinki bawah kaunter dengan permukaan dua lapis.' },
      { kind: 'Dapur', title: 'Dapur serba biru', text: 'Renovasi dapur penuh dengan kabinet tempahan berwarna biru.' },
      { kind: 'Ruang tamu', title: 'Ruang tamu minimalis', text: 'Kemasan bertekstur, lampu suasana dan sambungan yang kemas di sekeliling dinding TV.' },
      { kind: 'Ruang tamu', title: 'Dinding TV panel beralur', text: 'Panel beralur dengan lampu tersembunyi yang lembut, memberi kedalaman pada ruang tamu yang minimalis.' },
      { kind: 'Bilik air', title: 'Bilik air hijau dan biru', text: 'Jubin hijau dan biru dengan bucu melengkung, berlatarkan jubin putih 2×2 di dinding dan lantai.' },
      { kind: 'Bilik tidur', title: 'Perabot terbina dalam bilik tidur', text: 'Meja solek panel beralur dengan lampu suasana, almari pakaian tempahan dan kepala katil yang sepadan, dalam tona hangat.' },
      { kind: 'Pertukangan', title: '“Pintu ajaib”', text: 'Pintu gelangsar dengan trek tersembunyi dan tanpa rel di lantai, jadi ia nampak seperti terapung di sepanjang dinding.' },
      { kind: 'Bilik air', title: 'Bilik mandi hijau tua', text: 'Jubin hijau tua di ruang mandi, dinding neutral dan lantai terrazzo, dengan ceruk berlampu, tingkap kaca kabur dan kelengkapan hitam matte.' },
    ],
  },
  services: {
    kicker: 'Servis',
    title: 'Apa yang kami buat',
    free: 'Konsultasi reka bentuk dan sebut harga adalah percuma.',
    follow: 'Ikuti',
    teams: [
      { id: 'studio', name: 'EYCR Studio', role: 'Reka bentuk dalaman & renovasi', text: 'Dari satu bilik air hingga seluruh rumah: susun atur, kabinet dan almari tempahan, siling, lampu, jubin dan cat.', list: ['Reka bentuk dalaman', 'Renovasi dapur', 'Renovasi bilik air', 'Kabinet & almari tempahan', 'Siling & lampu', 'Jubin & cat'] },
      { id: 'aircond', name: 'EYCR Aircond & Electrical', role: 'Aircond & pendawaian', text: 'Kerja yang bersih dan profesional pada harga berpatutan, untuk rumah dan pejabat. Juruteknik kami berpengalaman lebih 8 tahun.', list: ['Servis aircond', 'Pasang & buka unit', 'Kenal pasti masalah', 'Baiki', 'Elektrik & pendawaian'] },
    ],
    jobsTitle: 'Kerja aircond & elektrik terkini',
    jobs: [
      'Buka dan pasang dua unit aircond inverter 1HP, sekali dengan paip salur baharu, pendawaian baharu dan flare nut baharu.',
      'Servis lebih 20 unit aircond dalam satu kerja.',
      'Tukar aircond dan paip kuprum di Villa Wangsamas.',
      'Servis lima unit aircond.',
    ],
    jobsCredit: 'Foto: EYCR Aircond di Instagram',
    tip: 'Tip kami: servis setiap unit setiap 3–6 bulan, cuci penapis selalu dan pastikan unit luar tidak terhalang.',
  },
  about: {
    kicker: 'Tentang kami',
    title: 'Tentang EYCR',
    paras: [
      'EY Creative Reno & Designs, atau EYCR, ialah syarikat renovasi dan servis di Wangsa Maju, Kuala Lumpur.',
      'Kami bekerja dalam dua pasukan. EYCR Studio mengendalikan reka bentuk dalaman dan renovasi: dapur, bilik air, ruang tamu, bilik tidur dan kerja kayu tempahan. EYCR Aircond & Electrical pula buat servis, pemasangan dan baik pulih aircond, serta kerja pendawaian.',
      'Banyak kerja terkini berdekatan pejabat kami, termasuk dapur dan kerja aircond di Villa Wangsamas.',
    ],
    facts: [['Syarikat', 'EY Creative Reno & Designs (EYCR)'], ['Lokasi', 'Wangsa Maju, Kuala Lumpur'], ['Waktu', 'Isnin–Sabtu, 9 pg–6 ptg'], ['Penarafan Google', '4.8 daripada 17 ulasan']],
    stepsTitle: 'Cara dapatkan sebut harga',
    steps: [
      ['WhatsApp kami', 'Hantar beberapa gambar ruang atau unit aircond, dan lokasi anda.'],
      ['Konsultasi & sebut harga', 'Konsultasi reka bentuk dan sebut harga adalah percuma.'],
      ['Kerja bermula', 'Bila anda setuju dengan sebut harga, kami tetapkan tarikh kerja.'],
    ],
  },
  reviews: {
    kicker: 'Ulasan',
    title: 'Kata pelanggan',
    sub: '4.8 daripada 17 ulasan Google',
    all: 'Baca semua ulasan di Google',
    source: 'Ulasan Google',
    prev: 'Ulasan sebelumnya',
    next: 'Ulasan seterusnya',
    region: 'Ulasan pelanggan, leret untuk lagi',
    origNote: 'Ulasan asal dalam Bahasa Inggeris.',
    items: [
      { tag: 'Elektrik', date: '2026-02-04', text: en.reviews.items[0].text },
      { tag: 'Aircond', date: '2026-01-06', text: en.reviews.items[1].text },
      { tag: 'Renovasi', date: '2023-10-26', text: en.reviews.items[2].text },
      { tag: 'Servis', date: '2026-01-07', text: en.reviews.items[3].text },
      { tag: 'Aircond + elektrik', date: '2022-12-29', text: en.reviews.items[4].text },
    ],
  },
  faq: {
    kicker: 'Soalan lazim',
    title: 'Soalan biasa',
    items: [
      ['Betul ke konsultasi percuma?', 'Ya. Konsultasi reka bentuk dan sebut harga adalah percuma. WhatsApp kami beberapa gambar dan lokasi anda untuk mula.'],
      ['Kawasan mana yang anda liputi?', 'Kami di Wangsa Maju, Kuala Lumpur. Hantar lokasi anda di WhatsApp dan kami akan sahkan sama ada kami boleh datang.'],
      ['Berapa kerap aircond patut diservis?', 'Setiap 3 hingga 6 bulan. Cuci penapis selalu di antara servis dan pastikan unit luar tidak terhalang.'],
      ['Apa yang perlu saya hantar untuk masalah aircond?', 'Gambar unit dalaman dan labelnya (jenama dan model), apa yang berlaku (tak sejuk, air menitis, bising), berapa unit, dan anggaran bila kali terakhir diservis.'],
      ['Elektrik asyik trip. Apa patut saya buat?', 'Kalau ada bau terbakar, percikan api atau asap, tutup suis utama di kotak DB, jauhkan diri dan telefon kami. Untuk trip atau sebahagian bekalan terputus, WhatsApp gambar kotak DB dan beritahu apa yang sedang dihidupkan semasa ia trip.'],
    ],
  },
  contact: {
    kicker: 'Hubungi',
    title: 'Hubungi kami',
    sub: 'WhatsApp paling cepat. Hantar beberapa gambar dan lokasi anda, dan kami akan balas dalam waktu bekerja.',
    phone: 'Telefon & WhatsApp',
    email: 'E-mel',
    address: 'Alamat',
    hours: 'Waktu operasi',
    days: [['Isnin–Sabtu', '9 pg – 6 ptg'], ['Ahad', 'Tutup']],
    today: 'Hari ini',
    maps: 'Buka di Google Maps',
    directions: 'Dapatkan arah',
    follow: 'Ikuti kami',
    links: 'Semua pautan',
    mapAlt: 'Peta Wangsa Maju menunjukkan lokasi EYCR berhampiran Jalan Seri Wangsa',
    mapCredit: 'Peta © penyumbang OpenStreetMap',
    waMsg: 'Hai EYCR, saya nak tanya tentang satu kerja.',
    waQuote: 'Hai EYCR, saya nak dapatkan konsultasi dan sebut harga percuma.',
  },
  footer: {
    blurb: 'Reka bentuk dalaman, renovasi, aircond dan kerja elektrik di Wangsa Maju, Kuala Lumpur.',
    explore: 'Laman',
    reach: 'Hubungi',
    photos: 'Foto: @eycrstudio dan @eycraircond di Instagram.',
    rights: 'Hak cipta terpelihara.',
    pitch: 'Konsep laman web disediakan untuk studio ini. Bukan laman rasmi lagi — sedia dijadikan milik anda.',
    pitchLink: 'Hubungi pereka',
  },
}

export const content = { en, ms }
