export type TradeId = 'aircon' | 'electrical' | 'reno' | 'interior'

export const BIZ = {
  name: 'EY Creative Reno & Designs',
  phone: '+60 10-233 0434',
  tel: '+60102330434',
  wa: '60102330434',
  address: 'Jalan Seri Wangsa 2, Wangsa Maju, 53300 Kuala Lumpur',
  maps: 'https://www.google.com/maps/place/EY+Creative+Reno+%26+Designs/@3.194511,101.7375491,17z',
  directions: 'https://www.google.com/maps/dir/?api=1&destination=3.194511,101.737549',
  rating: '4.8',
  reviews: 17,
}

const en = {
  meta: {
    title: 'EY Creative Reno & Designs | Renovation, Electrical, Air-Cond & Interior Design in Wangsa Maju, KL',
    desc: 'One team for renovation, electrical work, air-conditioning and interior design in Wangsa Maju, Kuala Lumpur. Rated 4.8 on Google. Build a job ticket and send it on WhatsApp.',
  },
  langLabel: 'BM',
  langAria: 'BM · Tukar ke Bahasa Melayu',
  a11y: { skip: 'Skip to content', main: 'Main', mobile: 'Mobile menu', menuOpen: 'Open menu', menuClose: 'Close menu', toTop: 'Back to top', bar: 'Quick contact' },
  nav: [['trades', 'Services'], ['how', 'How we work'], ['reviews', 'Reviews'], ['ticket', 'Get a quote'], ['contact', 'Contact']] as [string, string][],
  status: { open: 'Open now', closes: 'until 6 PM', closed: 'Closed', opensToday: 'opens 9 AM', opensTomorrow: 'opens 9 AM tomorrow', opensMon: 'opens Mon 9 AM' },
  waCta: 'WhatsApp',
  call: 'Call',
  hero: {
    eyebrow: 'Wangsa Maju · Kuala Lumpur',
    h1: ['One call.', 'Four trades.', 'One team.'],
    sub: 'Renovation, electrical, air-cond and interior design, planned together and done by one crew.',
    cta: 'Get a quote',
    cta2: 'WhatsApp us now',
    hours: 'Mon–Sat',
    area: 'Wangsa Maju',
    reviewsWord: 'Google reviews',
    photo: 'Illustrative photo',
  },
  trades: {
    kicker: 'Services',
    title: 'What we take on.',
    note: 'Typical jobs, not the full list. Flip a switch to add a trade to your quote.',
    add: 'Add to quote',
    added: 'In your quote',
    selOne: 'trade in your quote',
    selMany: 'trades in your quote',
    go: 'Continue',
    unsure: 'Not sure where your job fits? Describe it on WhatsApp',
    region: 'Services, swipe for more',
    prev: 'Previous service',
    next: 'Next service',
    items: [
      { id: 'reno' as TradeId, name: 'Renovation', line: 'One bathroom or the whole home, built neatly and handed back clean.', jobs: ['Kitchen', 'Bathroom', 'Tiling', 'Plaster ceiling', 'Painting', 'Full-home renovation'] },
      { id: 'electrical' as TradeId, name: 'Electrical', line: 'Faults found and fixed properly, from tripping to new points.', jobs: ['Tripping & power cuts', 'Wiring faults', 'Lights, fans & switches', 'Power points', 'Rewiring during renovation'] },
      { id: 'aircon' as TradeId, name: 'Air-cond', line: 'Servicing, repairs and new units, so the room gets cold and stays cold.', jobs: ['Servicing & cleaning', 'Not cold or weak airflow', 'Water leaking', 'Parts replacement', 'New units & installation'] },
      { id: 'interior' as TradeId, name: 'Interior design', line: 'A plan for how the space looks and works, built by the same team.', jobs: ['Layout planning', 'Colours & finishes', 'Lighting', 'Built-ins & storage', 'Whole-home design'] },
    ],
    alt: { aircon: 'Wall-mounted split air-conditioner', electrical: 'Open distribution board with circuit breakers', reno: 'Hands fitting wall tiles', interior: 'Condo living room with TV console and curtains' },
  },
  how: {
    kicker: 'How we work',
    title: 'Fewer handovers. Fewer surprises.',
    usual: 'The usual way',
    ey: 'With EY',
    rows: [
      ['Four companies for one home', 'One team for all four trades'],
      ['You coordinate everyone', 'One WhatsApp thread'],
      ['Wiring squeezed in after the ceiling', 'Wiring and aircond points planned first'],
      ['Four quotations to compare', 'One written quotation'],
      ['Who do you call afterwards?', 'One number after handover'],
    ] as [string, string][],
    stepsTitle: 'From message to clean finish',
    steps: [
      ['Message', 'WhatsApp the job, a few photos and your area.'],
      ['Site check', 'The problem is seen in person, not guessed.'],
      ['Quotation', 'Scope and price agreed in writing before work starts.'],
      ['Done & tidy', 'Work explained to you, and the area cleaned after.'],
    ] as [string, string][],
  },
  ticket: {
    kicker: 'Get a quote',
    title: 'One message. Every job.',
    sub: 'Tick what needs doing. We turn it into one WhatsApp message, so you only explain it once.',
    step1: 'Trades',
    step2: 'The job',
    step3: 'Property',
    step4: 'Area',
    step5: 'Timing',
    step6: 'Anything else?',
    optional: 'optional',
    areaPh: 'e.g. Wangsa Maju, Setapak',
    notePh: 'e.g. 3 units in a condo, last serviced a year ago',
    pickTrade: 'Choose at least one trade above.',
    property: ['Condo / apartment', 'Landed house', 'Shop / office'],
    timing: ['As soon as possible', 'This week', 'Just planning'],
    card: { title: 'Job ticket', draft: 'Draft', jobs: 'Jobs', property: 'Property', area: 'Area', timing: 'Timing', note: 'Note', empty: 'Nothing selected yet', none: 'Not given' },
    send: 'Send ticket on WhatsApp',
    sendHint: 'Opens WhatsApp with the ticket filled in. Nothing is sent until you press send.',
    reset: 'Clear',
    msgHi: 'Hi EY Creative Reno & Designs, I’d like a quote.',
    msgJobs: 'Jobs',
    msgProperty: 'Property',
    msgArea: 'Area',
    msgTiming: 'Timing',
    msgNote: 'Note',
    msgPhotos: 'I can send photos.',
    general: 'general enquiry',
  },
  reviews: {
    kicker: 'Reviews',
    title: 'In customers’ words.',
    sub: 'Rated 4.8 from 17 Google reviews.',
    all: 'Read all on Google',
    prev: 'Previous review',
    next: 'Next review',
    region: 'Customer reviews, swipe for more',
    origNote: '',
    items: [
      { tag: 'Electrical', date: '2026-02-04', text: 'Excellent service as always. Had to call for wiring issue as urgent matter today and their staff dealt with it swiftly and professionally. Job well done.' },
      { tag: 'Air-cond', date: '2026-01-06', text: 'Excellent air-conditioning service. The staff were friendly and explained the issue clearly before starting the work. Service was fast and neat, and the air-cond is much colder after servicing.' },
      { tag: 'Renovation', date: '2023-10-26', text: 'I really can’t say enough good things about this company … This was a 1-month renovation and it was right on schedule, start to finish.' },
      { tag: 'Service', date: '2026-01-07', text: 'Good customer service, … punctual, and cleans the area after work.' },
      { tag: 'Air-cond + electrical', date: '2022-12-29', text: 'Highly recommended. Reliable. Friendly … showed up on time, friendly, patient, clean and most of all sincere.' },
    ],
  },
  faq: {
    kicker: 'FAQ',
    title: 'Good questions to ask first.',
    items: [
      ['Can one team really handle reno, wiring and air-cond?', 'Renovation, electrical work, air-conditioning and interior design are all services of EY Creative Reno & Designs. Put every job in one message and they can be planned together, so wiring and aircond points are ready before the ceiling and paint go up.'],
      ['Will I get a quotation before work starts?', 'You should, from any contractor. Ask for a written, itemised quotation and agree it before work begins. It’s the easiest way to compare and avoid surprises.'],
      ['Which areas do you cover?', 'We’re based in Wangsa Maju, Kuala Lumpur. Send your location on WhatsApp and we’ll confirm whether we can come to you.'],
      ['What are your hours?', 'Monday to Saturday, 9 AM–6 PM. Closed on Sunday. You can WhatsApp anytime and we’ll reply during working hours.'],
      ['What should I send for an air-cond problem?', 'A photo of the indoor unit and its label (brand and model), what’s happening (not cold, leaking, noisy), how many units, and roughly when it was last serviced.'],
      ['The power keeps tripping. What should I do?', 'If you notice a burning smell, sparks or smoke, switch off the main switch at the DB box, keep clear and call. For tripping or a partial power cut, WhatsApp a photo of the DB box and tell us what was switched on when it tripped.'],
    ] as [string, string][],
  },
  contact: {
    kicker: 'Contact',
    title: 'Tell us what needs fixing.',
    sub: 'WhatsApp a few photos for the quickest reply. Calls welcome during working hours.',
    address: 'Address',
    hours: 'Hours',
    days: [['Mon–Sat', '9 AM – 6 PM'], ['Sunday', 'Closed']] as [string, string][],
    today: 'Today',
    maps: 'Open in Google Maps',
    directions: 'Get directions',
    waMsg: 'Hi EY Creative Reno & Designs, I’d like to ask about a job.',
  },
  footer: {
    tagline: 'Renovation · Electrical · Air-cond · Interior design',
    photos: 'Photos are illustrative stock images (Unsplash), not EY projects.',
    toTop: 'Back to top',
    pitch: 'Website concept prepared for this studio. Not an official site yet — open to making it yours.',
    pitchLink: 'Talk to the designer',
    rights: 'All trademarks belong to their owners.',
  },
}

export type Content = typeof en

const ms: Content = {
  meta: {
    title: 'EY Creative Reno & Designs | Renovasi, Elektrik, Penghawa Dingin & Reka Bentuk Dalaman di Wangsa Maju, KL',
    desc: 'Satu pasukan untuk renovasi, kerja elektrik, penghawa dingin dan reka bentuk dalaman di Wangsa Maju, Kuala Lumpur. Penarafan 4.8 di Google. Sediakan tiket kerja dan hantar melalui WhatsApp.',
  },
  langLabel: 'EN',
  langAria: 'EN · Switch to English',
  a11y: { skip: 'Langkau ke kandungan', main: 'Utama', mobile: 'Menu mudah alih', menuOpen: 'Buka menu', menuClose: 'Tutup menu', toTop: 'Kembali ke atas', bar: 'Hubungi pantas' },
  nav: [['trades', 'Perkhidmatan'], ['how', 'Cara kerja'], ['reviews', 'Ulasan'], ['ticket', 'Sebut harga'], ['contact', 'Hubungi']],
  status: { open: 'Dibuka sekarang', closes: 'hingga 6 PTG', closed: 'Ditutup', opensToday: 'dibuka 9 PG', opensTomorrow: 'dibuka 9 PG esok', opensMon: 'dibuka Isnin 9 PG' },
  waCta: 'WhatsApp',
  call: 'Telefon',
  hero: {
    eyebrow: 'Wangsa Maju · Kuala Lumpur',
    h1: ['Satu panggilan.', 'Empat bidang.', 'Satu pasukan.'],
    sub: 'Renovasi, elektrik, aircond dan reka bentuk dalaman, dirancang bersama dan disiapkan oleh satu pasukan.',
    cta: 'Dapatkan sebut harga',
    cta2: 'WhatsApp kami sekarang',
    hours: 'Isnin–Sabtu',
    area: 'Wangsa Maju',
    reviewsWord: 'ulasan Google',
    photo: 'Foto ilustrasi',
  },
  trades: {
    kicker: 'Perkhidmatan',
    title: 'Kerja yang kami ambil.',
    note: 'Contoh kerja biasa, bukan senarai penuh. Hidupkan suis untuk tambah bidang ke sebut harga anda.',
    add: 'Tambah ke sebut harga',
    added: 'Dalam sebut harga',
    selOne: 'bidang dalam sebut harga',
    selMany: 'bidang dalam sebut harga',
    go: 'Teruskan',
    unsure: 'Tak pasti kerja anda di bawah yang mana? Terangkan di WhatsApp',
    region: 'Perkhidmatan, leret untuk lagi',
    prev: 'Perkhidmatan sebelumnya',
    next: 'Perkhidmatan seterusnya',
    items: [
      { id: 'reno', name: 'Renovasi', line: 'Satu bilik air atau seluruh rumah, dibina kemas dan diserahkan bersih.', jobs: ['Dapur', 'Bilik air', 'Jubin', 'Siling plaster', 'Mengecat', 'Renovasi seluruh rumah'] },
      { id: 'electrical', name: 'Elektrik', line: 'Kerosakan dicari dan dibaiki dengan betul, dari trip hingga soket baharu.', jobs: ['Trip & bekalan terputus', 'Pendawaian rosak', 'Lampu, kipas & suis', 'Soket kuasa', 'Pendawaian semula semasa renovasi'] },
      { id: 'aircon', name: 'Aircond', line: 'Servis, pembaikan dan unit baharu, supaya bilik sejuk dan kekal sejuk.', jobs: ['Servis & cuci', 'Tak sejuk atau angin lemah', 'Air menitis', 'Tukar alat ganti', 'Unit baharu & pemasangan'] },
      { id: 'interior', name: 'Reka bentuk dalaman', line: 'Pelan rupa dan fungsi ruang anda, dibina oleh pasukan yang sama.', jobs: ['Susun atur', 'Warna & kemasan', 'Pencahayaan', 'Kabinet terbina dalam & storan', 'Reka bentuk seluruh rumah'] },
    ],
    alt: { aircon: 'Penghawa dingin jenis split di dinding', electrical: 'Kotak agihan elektrik (DB) yang terbuka', reno: 'Tangan memasang jubin dinding', interior: 'Ruang tamu kondo dengan kabinet TV dan langsir' },
  },
  how: {
    kicker: 'Cara kerja',
    title: 'Kurang serahan. Kurang kejutan.',
    usual: 'Cara biasa',
    ey: 'Dengan EY',
    rows: [
      ['Empat syarikat untuk satu rumah', 'Satu pasukan untuk empat bidang'],
      ['Anda yang menyelaras semua', 'Satu perbualan WhatsApp'],
      ['Pendawaian diselit selepas siling siap', 'Titik pendawaian dan aircond dirancang dulu'],
      ['Empat sebut harga untuk dibanding', 'Satu sebut harga bertulis'],
      ['Siapa nak dihubungi selepas itu?', 'Satu nombor selepas serahan'],
    ],
    stepsTitle: 'Dari mesej hingga siap dan bersih',
    steps: [
      ['Mesej', 'WhatsApp kerjanya, beberapa gambar dan kawasan anda.'],
      ['Semakan tapak', 'Masalah dilihat sendiri, bukan diteka.'],
      ['Sebut harga', 'Skop dan harga dipersetujui secara bertulis sebelum kerja bermula.'],
      ['Siap & kemas', 'Kerja diterangkan kepada anda, dan kawasan dibersihkan selepas itu.'],
    ],
  },
  ticket: {
    kicker: 'Sebut harga',
    title: 'Satu mesej. Semua kerja.',
    sub: 'Tandakan apa yang perlu dibuat. Kami jadikannya satu mesej WhatsApp, jadi anda cuma terangkan sekali.',
    step1: 'Bidang',
    step2: 'Kerjanya',
    step3: 'Kediaman',
    step4: 'Kawasan',
    step5: 'Bila',
    step6: 'Ada lagi?',
    optional: 'pilihan',
    areaPh: 'cth. Wangsa Maju, Setapak',
    notePh: 'cth. 3 unit di kondo, kali terakhir diservis setahun lalu',
    pickTrade: 'Pilih sekurang-kurangnya satu bidang di atas.',
    property: ['Kondo / apartmen', 'Rumah bertanah', 'Kedai / pejabat'],
    timing: ['Secepat mungkin', 'Minggu ini', 'Masih merancang'],
    card: { title: 'Tiket kerja', draft: 'Draf', jobs: 'Kerja', property: 'Kediaman', area: 'Kawasan', timing: 'Bila', note: 'Nota', empty: 'Belum ada pilihan', none: 'Tiada' },
    send: 'Hantar tiket melalui WhatsApp',
    sendHint: 'WhatsApp akan dibuka dengan tiket sudah diisi. Tiada apa dihantar sehingga anda tekan hantar.',
    reset: 'Kosongkan',
    msgHi: 'Hai EY Creative Reno & Designs, saya ingin dapatkan sebut harga.',
    msgJobs: 'Kerja',
    msgProperty: 'Kediaman',
    msgArea: 'Kawasan',
    msgTiming: 'Bila',
    msgNote: 'Nota',
    msgPhotos: 'Saya boleh hantar gambar.',
    general: 'pertanyaan umum',
  },
  reviews: {
    kicker: 'Ulasan',
    title: 'Kata pelanggan.',
    sub: 'Penarafan 4.8 daripada 17 ulasan Google.',
    all: 'Baca semua di Google',
    prev: 'Ulasan sebelumnya',
    next: 'Ulasan seterusnya',
    region: 'Ulasan pelanggan, leret untuk lagi',
    origNote: 'Ulasan asal dalam Bahasa Inggeris.',
    items: [
      { tag: 'Elektrik', date: '2026-02-04', text: en.reviews.items[0].text },
      { tag: 'Aircond', date: '2026-01-06', text: en.reviews.items[1].text },
      { tag: 'Renovasi', date: '2023-10-26', text: en.reviews.items[2].text },
      { tag: 'Servis', date: '2026-01-07', text: en.reviews.items[3].text },
      { tag: 'Aircond + elektrik', date: '2022-12-29', text: en.reviews.items[4].text },
    ],
  },
  faq: {
    kicker: 'Soalan lazim',
    title: 'Soalan yang wajar ditanya dulu.',
    items: [
      ['Betulkah satu pasukan boleh urus renovasi, pendawaian dan aircond?', 'Renovasi, kerja elektrik, penghawa dingin dan reka bentuk dalaman semuanya perkhidmatan EY Creative Reno & Designs. Masukkan semua kerja dalam satu mesej supaya ia dirancang bersama, jadi titik pendawaian dan aircond siap sebelum siling dan cat.'],
      ['Adakah saya akan dapat sebut harga sebelum kerja bermula?', 'Sepatutnya, daripada mana-mana kontraktor. Minta sebut harga bertulis yang terperinci dan setujuinya sebelum kerja bermula. Itu cara paling mudah untuk membandingkan dan mengelakkan kejutan.'],
      ['Kawasan mana yang anda liputi?', 'Kami berpangkalan di Wangsa Maju, Kuala Lumpur. Hantar lokasi anda di WhatsApp dan kami akan sahkan sama ada kami boleh datang.'],
      ['Bila waktu operasi?', 'Isnin hingga Sabtu, 9 PG–6 PTG. Ditutup pada hari Ahad. Anda boleh WhatsApp bila-bila masa dan kami akan balas dalam waktu bekerja.'],
      ['Apa yang perlu saya hantar untuk masalah aircond?', 'Gambar unit dalaman dan labelnya (jenama dan model), apa yang berlaku (tak sejuk, menitis, bising), berapa unit, dan anggaran bila kali terakhir diservis.'],
      ['Bekalan elektrik asyik trip. Apa patut saya buat?', 'Jika ada bau terbakar, percikan api atau asap, tutup suis utama di kotak DB, jauhkan diri dan telefon. Untuk trip atau sebahagian bekalan terputus, WhatsApp gambar kotak DB dan beritahu apa yang sedang dihidupkan semasa ia trip.'],
    ],
  },
  contact: {
    kicker: 'Hubungi',
    title: 'Beritahu kami apa yang perlu dibaiki.',
    sub: 'WhatsApp beberapa gambar untuk balasan paling cepat. Panggilan dialu-alukan dalam waktu bekerja.',
    address: 'Alamat',
    hours: 'Waktu operasi',
    days: [['Isnin–Sabtu', '9 PG – 6 PTG'], ['Ahad', 'Ditutup']],
    today: 'Hari ini',
    maps: 'Buka di Google Maps',
    directions: 'Dapatkan arah',
    waMsg: 'Hai EY Creative Reno & Designs, saya ingin bertanya tentang satu kerja.',
  },
  footer: {
    tagline: 'Renovasi · Elektrik · Aircond · Reka bentuk dalaman',
    photos: 'Foto ialah imej stok ilustrasi (Unsplash), bukan projek EY.',
    toTop: 'Kembali ke atas',
    pitch: 'Konsep laman web disediakan untuk studio ini. Bukan laman rasmi lagi — sedia dijadikan milik anda.',
    pitchLink: 'Hubungi pereka',
    rights: 'Semua tanda dagangan milik pemiliknya.',
  },
}

export const content = { en, ms }
