export type TradeId = 'aircon' | 'electrical' | 'reno' | 'interior'

export const BIZ = {
  name: 'EY Creative Reno & Designs',
  phone: '+60 10-233 0434',
  tel: '+60102330434',
  wa: '60102330434',
  address: 'Jalan Seri Wangsa 2, Wangsa Maju, 53300 Kuala Lumpur',
  maps: 'https://www.google.com/maps/place/EY+Creative+Reno+%26+Designs/@3.194511,101.7375491,17z',
  directions: 'https://www.google.com/maps/dir/?api=1&destination=3.194511,101.737549',
  rating: '4.8',
  reviews: 17,
}

const en = {
  meta: {
    title: 'EY Creative Reno & Designs | Renovation, Electrical, Air-Cond & Interior Design in Wangsa Maju, KL',
    desc: 'One team for renovation, electrical work, air-conditioning and interior design in Wangsa Maju, Kuala Lumpur. Rated 4.8 on Google. Build a job ticket and send it on WhatsApp.',
  },
  langLabel: 'BM',
  langAria: 'BM, tukar ke Bahasa Melayu',
  a11y: { skip: 'Skip to content', main: 'Main', mobile: 'Mobile menu', menuOpen: 'Open menu', menuClose: 'Close menu', toTop: 'Back to top', fab: 'WhatsApp EY Creative Reno & Designs' },
  nav: [['trades', 'Services'], ['ticket', 'Get a quote'], ['reviews', 'Reviews'], ['faq', 'FAQ'], ['contact', 'Contact']] as [string, string][],
  status: { open: 'Open now', closes: 'until 6 PM', closed: 'Closed', opensToday: 'opens 9 AM', opensTomorrow: 'opens 9 AM tomorrow', opensMon: 'opens Mon 9 AM' },
  waCta: 'WhatsApp',
  hero: {
    eyebrow: 'Wangsa Maju · Kuala Lumpur',
    h1a: 'One call for the reno,',
    h1b: 'the wiring, the air-cond',
    h1c: 'and the look.',
    sub: 'EY Creative Reno & Designs brings renovation, electrical work, air-conditioning and interior design under one team, so the trades plan together instead of working around each other.',
    cta: 'Start a job ticket',
    cta2: 'WhatsApp us',
    rating: 'on Google',
    reviewsWord: 'reviews',
    hub: 'EY',
    nodes: { reno: 'Renovation', electrical: 'Electrical', aircon: 'Air-cond', interior: 'Interior' },
    photo: 'Illustrative photo',
  },
  strip: ['Renovation', 'Electrical', 'Air-conditioning', 'Interior design', 'Mon–Sat 9 AM–6 PM'],
  trades: {
    eyebrow: 'Four trades · one team',
    title: 'What you can call us for.',
    note: 'Typical jobs, not a full list. Not sure where your job fits? Describe it on WhatsApp.',
    items: [
      { id: 'aircon' as TradeId, code: 'AC', name: 'Air-conditioning', line: 'Servicing, repairs and new units, so the room gets cold again and stays that way.', jobs: ['Servicing & cleaning', 'Not cold or weak airflow', 'Water leaking', 'Parts replacement', 'New units & installation'] },
      { id: 'electrical' as TradeId, code: 'EL', name: 'Electrical', line: 'Faults found and fixed properly: tripping, wiring, lights and power points.', jobs: ['Tripping & power cuts', 'Wiring faults', 'Lights, fans & switches', 'Power points', 'Rewiring during renovation'] },
      { id: 'reno' as TradeId, code: 'RN', name: 'Renovation', line: 'From one bathroom to the whole home, built neatly and handed back clean.', jobs: ['Kitchen', 'Bathroom', 'Tiling', 'Plaster ceiling', 'Painting', 'Full-home renovation'] },
      { id: 'interior' as TradeId, code: 'ID', name: 'Interior design', line: 'A plan for how the space should look and work, built by the same team.', jobs: ['Layout planning', 'Colours & finishes', 'Lighting', 'Built-ins & storage', 'Whole-home design'] },
    ],
    alt: { aircon: 'Wall-mounted split air-conditioner', electrical: 'Open distribution board with circuit breakers', reno: 'Hands fitting wall tiles', interior: 'Finished condo living room with sofa and TV console' },
  },
  oneteam: {
    eyebrow: 'Why one team',
    title: 'Fewer handovers. Fewer surprises.',
    usualTitle: 'The usual way',
    usual: ['A contractor for the reno', 'An electrician for the wiring', 'An aircond company for the units', 'A designer for the look', 'You, in the middle, coordinating all four'],
    eyTitle: 'With EY',
    ey: ['One WhatsApp thread for every trade', 'Wiring and aircond points planned before the ceiling goes up', 'One schedule, one team on site', 'One quotation to compare', 'One number to call after handover'],
    photo: 'Renovation in progress. Illustrative photo.',
    alt: 'Room stripped back during renovation with temporary ceiling props',
  },
  ticket: {
    eyebrow: 'Get a quote',
    title: 'Build a job ticket.',
    sub: 'Tick what needs doing. We’ll turn it into one WhatsApp message, so you only explain the job once.',
    step1: '1 · Which trades?',
    step2: '2 · What’s the job?',
    step3: '3 · Property',
    step4: '4 · Area',
    step5: '5 · Timing',
    step6: 'Anything else? (optional)',
    areaPh: 'e.g. Wangsa Maju, Setapak',
    notePh: 'e.g. 3 units in a condo, last serviced a year ago',
    pickTrade: 'Choose at least one trade above.',
    property: ['Condo / apartment', 'Landed house', 'Shop / office'],
    timing: ['As soon as possible', 'This week', 'Just planning'],
    card: { title: 'Job ticket', draft: 'Draft', jobs: 'Jobs', property: 'Property', area: 'Area', timing: 'Timing', note: 'Note', empty: 'Nothing selected yet', none: 'Not given' },
    send: 'Send ticket on WhatsApp',
    sendHint: 'Opens WhatsApp with the ticket filled in. Nothing is sent until you press send.',
    reset: 'Clear',
    msgHi: 'Hi EY Creative Reno & Designs, I’d like a quote.',
    msgJobs: 'Jobs',
    msgProperty: 'Property',
    msgArea: 'Area',
    msgTiming: 'Timing',
    msgNote: 'Note',
    msgPhotos: 'I can send photos.',
    general: 'general enquiry',
  },
  reviews: {
    eyebrow: 'Reviews',
    title: 'What customers wrote.',
    sub: 'Rated 4.8 from 17 Google reviews. Excerpts below, in the customers’ own words.',
    all: 'Read all reviews on Google',
    origNote: '',
    items: [
      { tag: 'Electrical', date: '2026-02-04', text: 'Excellent service as always. Had to call for wiring issue as urgent matter today and their staff dealt with it swiftly and professionally. Job well done.' },
      { tag: 'Air-cond', date: '2026-01-06', text: 'Excellent air-conditioning service. The staff were friendly and explained the issue clearly before starting the work. Service was fast and neat, and the air-cond is much colder after servicing.' },
      { tag: 'Renovation', date: '2023-10-26', text: 'I really can’t say enough good things about this company … This was a 1-month renovation and it was right on schedule, start to finish.' },
      { tag: 'Service', date: '2026-01-07', text: 'Good customer service, … punctual, and cleans the area after work.' },
      { tag: 'Air-cond + electrical', date: '2022-12-29', text: 'Highly recommended. Reliable. Friendly … showed up on time, friendly, patient, clean and most of all sincere.' },
    ],
  },
  process: {
    eyebrow: 'How it works',
    title: 'From message to clean finish.',
    steps: [
      ['Message', 'WhatsApp what’s wrong or what you want built, with photos and your area.'],
      ['Site check', 'Book a visit so the problem is seen, not guessed, and measurements are real.'],
      ['Quotation', 'Agree the scope and price in writing before any work starts.'],
      ['Done & tidy', 'Work carried out neatly, explained to you, and the area cleaned after.'],
    ] as [string, string][],
  },
  faq: {
    eyebrow: 'FAQ',
    title: 'Good questions to ask first.',
    items: [
      ['Can one team really handle reno, wiring and air-cond?', 'Renovation, electrical work, air-conditioning and interior design are all services of EY Creative Reno & Designs. Put every job in one message and they can be planned together, so wiring and aircond points are ready before the ceiling and paint go up.'],
      ['Will I get a quotation before work starts?', 'You should, from any contractor. Ask for a written, itemised quotation and agree it before work begins. It’s the easiest way to compare and avoid surprises.'],
      ['Which areas do you cover?', 'We’re based in Wangsa Maju, Kuala Lumpur. Send your location on WhatsApp and we’ll confirm whether we can come to you.'],
      ['What are your hours?', 'Monday to Saturday, 9 AM–6 PM. Closed on Sunday. You can WhatsApp anytime and we’ll reply during working hours.'],
      ['What should I send for an air-cond problem?', 'A photo of the indoor unit and its label (brand and model), what’s happening (not cold, leaking, noisy), how many units, and roughly when it was last serviced.'],
      ['The power keeps tripping. What should I do?', 'If you notice a burning smell, sparks or smoke, switch off the main switch at the DB box, keep clear and call. For tripping or a partial power cut, WhatsApp a photo of the DB box and tell us what was switched on when it tripped.'],
    ] as [string, string][],
  },
  contact: {
    eyebrow: 'Contact',
    title: 'Tell us what needs fixing.',
    sub: 'The quickest way is WhatsApp with a few photos. Calls are welcome during working hours.',
    call: 'Call',
    whatsapp: 'WhatsApp',
    address: 'Address',
    hours: 'Hours',
    days: [['Mon–Sat', '9 AM – 6 PM'], ['Sunday', 'Closed']] as [string, string][],
    today: 'Today',
    maps: 'Open in Google Maps',
    directions: 'Get directions',
    waMsg: 'Hi EY Creative Reno & Designs, I’d like to ask about a job.',
  },
  footer: {
    tagline: 'Renovation · Electrical · Air-cond · Interior design',
    photos: 'Photos are illustrative stock images (Unsplash), not EY projects.',
    toTop: 'Back to top',
    pitch: 'Website concept prepared for this studio. Not an official site yet — open to making it yours.',
    pitchLink: 'Talk to the designer',
    rights: 'All trademarks belong to their owners.',
  },
}

export type Content = typeof en

const ms: Content = {
  meta: {
    title: 'EY Creative Reno & Designs | Renovasi, Elektrik, Penghawa Dingin & Reka Bentuk Dalaman di Wangsa Maju, KL',
    desc: 'Satu pasukan untuk renovasi, kerja elektrik, penghawa dingin dan reka bentuk dalaman di Wangsa Maju, Kuala Lumpur. Penarafan 4.8 di Google. Sediakan tiket kerja dan hantar melalui WhatsApp.',
  },
  langLabel: 'EN',
  langAria: 'EN, switch to English',
  a11y: { skip: 'Langkau ke kandungan', main: 'Utama', mobile: 'Menu mudah alih', menuOpen: 'Buka menu', menuClose: 'Tutup menu', toTop: 'Kembali ke atas', fab: 'WhatsApp EY Creative Reno & Designs' },
  nav: [['trades', 'Perkhidmatan'], ['ticket', 'Dapatkan sebut harga'], ['reviews', 'Ulasan'], ['faq', 'Soalan lazim'], ['contact', 'Hubungi']],
  status: { open: 'Dibuka sekarang', closes: 'hingga 6 PTG', closed: 'Ditutup', opensToday: 'dibuka 9 PG', opensTomorrow: 'dibuka 9 PG esok', opensMon: 'dibuka Isnin 9 PG' },
  waCta: 'WhatsApp',
  hero: {
    eyebrow: 'Wangsa Maju · Kuala Lumpur',
    h1a: 'Satu panggilan untuk renovasi,',
    h1b: 'pendawaian, aircond',
    h1c: 'dan rekaan.',
    sub: 'EY Creative Reno & Designs menghimpunkan renovasi, kerja elektrik, penghawa dingin dan reka bentuk dalaman dalam satu pasukan, supaya semua kerja dirancang bersama, bukan berasingan.',
    cta: 'Mula tiket kerja',
    cta2: 'WhatsApp kami',
    rating: 'di Google',
    reviewsWord: 'ulasan',
    hub: 'EY',
    nodes: { reno: 'Renovasi', electrical: 'Elektrik', aircon: 'Aircond', interior: 'Dalaman' },
    photo: 'Foto ilustrasi',
  },
  strip: ['Renovasi', 'Elektrik', 'Penghawa dingin', 'Reka bentuk dalaman', 'Isnin–Sabtu 9 PG–6 PTG'],
  trades: {
    eyebrow: 'Empat bidang · satu pasukan',
    title: 'Apa yang boleh kami bantu.',
    note: 'Contoh kerja biasa, bukan senarai penuh. Tak pasti kerja anda di bawah yang mana? Terangkan di WhatsApp.',
    items: [
      { id: 'aircon', code: 'AC', name: 'Penghawa dingin', line: 'Servis, pembaikan dan unit baharu, supaya bilik kembali sejuk dan kekal sejuk.', jobs: ['Servis & cuci', 'Tak sejuk atau angin lemah', 'Air menitis', 'Tukar alat ganti', 'Unit baharu & pemasangan'] },
      { id: 'electrical', code: 'EL', name: 'Elektrik', line: 'Kerosakan dicari dan dibaiki dengan betul: trip, pendawaian, lampu dan soket.', jobs: ['Trip & bekalan terputus', 'Pendawaian rosak', 'Lampu, kipas & suis', 'Soket kuasa', 'Pendawaian semula semasa renovasi'] },
      { id: 'reno', code: 'RN', name: 'Renovasi', line: 'Dari satu bilik air hingga seluruh rumah, dibina kemas dan diserahkan bersih.', jobs: ['Dapur', 'Bilik air', 'Jubin', 'Siling plaster', 'Mengecat', 'Renovasi seluruh rumah'] },
      { id: 'interior', code: 'ID', name: 'Reka bentuk dalaman', line: 'Pelan rupa dan fungsi ruang anda, dibina oleh pasukan yang sama.', jobs: ['Susun atur', 'Warna & kemasan', 'Pencahayaan', 'Kabinet terbina dalam & storan', 'Reka bentuk seluruh rumah'] },
    ],
    alt: { aircon: 'Penghawa dingin jenis split di dinding', electrical: 'Kotak agihan elektrik (DB) yang terbuka', reno: 'Tangan memasang jubin dinding', interior: 'Ruang tamu kondo yang siap dengan sofa dan kabinet TV' },
  },
  oneteam: {
    eyebrow: 'Kenapa satu pasukan',
    title: 'Kurang serahan. Kurang kejutan.',
    usualTitle: 'Cara biasa',
    usual: ['Kontraktor untuk renovasi', 'Juruelektrik untuk pendawaian', 'Syarikat aircond untuk unit', 'Pereka untuk rupa', 'Anda, di tengah-tengah, menyelaras keempat-empatnya'],
    eyTitle: 'Dengan EY',
    ey: ['Satu perbualan WhatsApp untuk semua kerja', 'Titik pendawaian dan aircond dirancang sebelum siling dipasang', 'Satu jadual, satu pasukan di tapak', 'Satu sebut harga untuk dibandingkan', 'Satu nombor untuk dihubungi selepas serahan'],
    photo: 'Renovasi sedang berjalan. Foto ilustrasi.',
    alt: 'Bilik yang dikosongkan semasa renovasi dengan tiang sokong sementara',
  },
  ticket: {
    eyebrow: 'Dapatkan sebut harga',
    title: 'Sediakan tiket kerja.',
    sub: 'Tandakan apa yang perlu dibuat. Kami jadikannya satu mesej WhatsApp, jadi anda cuma perlu terangkan sekali.',
    step1: '1 · Bidang apa?',
    step2: '2 · Apa kerjanya?',
    step3: '3 · Jenis kediaman',
    step4: '4 · Kawasan',
    step5: '5 · Bila',
    step6: 'Ada lagi? (pilihan)',
    areaPh: 'cth. Wangsa Maju, Setapak',
    notePh: 'cth. 3 unit di kondo, kali terakhir diservis setahun lalu',
    pickTrade: 'Pilih sekurang-kurangnya satu bidang di atas.',
    property: ['Kondo / apartmen', 'Rumah bertanah', 'Kedai / pejabat'],
    timing: ['Secepat mungkin', 'Minggu ini', 'Masih merancang'],
    card: { title: 'Tiket kerja', draft: 'Draf', jobs: 'Kerja', property: 'Kediaman', area: 'Kawasan', timing: 'Bila', note: 'Nota', empty: 'Belum ada pilihan', none: 'Tiada' },
    send: 'Hantar tiket melalui WhatsApp',
    sendHint: 'WhatsApp akan dibuka dengan tiket sudah diisi. Tiada apa dihantar sehingga anda tekan hantar.',
    reset: 'Kosongkan',
    msgHi: 'Hai EY Creative Reno & Designs, saya ingin dapatkan sebut harga.',
    msgJobs: 'Kerja',
    msgProperty: 'Kediaman',
    msgArea: 'Kawasan',
    msgTiming: 'Bila',
    msgNote: 'Nota',
    msgPhotos: 'Saya boleh hantar gambar.',
    general: 'pertanyaan umum',
  },
  reviews: {
    eyebrow: 'Ulasan',
    title: 'Kata pelanggan.',
    sub: 'Penarafan 4.8 daripada 17 ulasan Google. Petikan di bawah dalam kata-kata asal pelanggan.',
    all: 'Baca semua ulasan di Google',
    origNote: 'Ulasan asal dalam Bahasa Inggeris.',
    items: [
      { tag: 'Elektrik', date: '2026-02-04', text: en.reviews.items[0].text },
      { tag: 'Aircond', date: '2026-01-06', text: en.reviews.items[1].text },
      { tag: 'Renovasi', date: '2023-10-26', text: en.reviews.items[2].text },
      { tag: 'Servis', date: '2026-01-07', text: en.reviews.items[3].text },
      { tag: 'Aircond + elektrik', date: '2022-12-29', text: en.reviews.items[4].text },
    ],
  },
  process: {
    eyebrow: 'Cara kerja',
    title: 'Dari mesej hingga siap dan bersih.',
    steps: [
      ['Mesej', 'WhatsApp masalah atau apa yang anda mahu dibina, bersama gambar dan kawasan anda.'],
      ['Semakan tapak', 'Tetapkan lawatan supaya masalah dilihat sendiri, bukan diteka, dan ukuran tepat.'],
      ['Sebut harga', 'Persetujui skop dan harga secara bertulis sebelum kerja bermula.'],
      ['Siap & kemas', 'Kerja dibuat dengan kemas, diterangkan kepada anda, dan kawasan dibersihkan selepas itu.'],
    ],
  },
  faq: {
    eyebrow: 'Soalan lazim',
    title: 'Soalan yang wajar ditanya dulu.',
    items: [
      ['Betulkah satu pasukan boleh urus renovasi, pendawaian dan aircond?', 'Renovasi, kerja elektrik, penghawa dingin dan reka bentuk dalaman semuanya perkhidmatan EY Creative Reno & Designs. Masukkan semua kerja dalam satu mesej supaya ia dirancang bersama, jadi titik pendawaian dan aircond siap sebelum siling dan cat.'],
      ['Adakah saya akan dapat sebut harga sebelum kerja bermula?', 'Sepatutnya, daripada mana-mana kontraktor. Minta sebut harga bertulis yang terperinci dan setujuinya sebelum kerja bermula. Itu cara paling mudah untuk membandingkan dan mengelakkan kejutan.'],
      ['Kawasan mana yang anda liputi?', 'Kami berpangkalan di Wangsa Maju, Kuala Lumpur. Hantar lokasi anda di WhatsApp dan kami akan sahkan sama ada kami boleh datang.'],
      ['Bila waktu operasi?', 'Isnin hingga Sabtu, 9 PG–6 PTG. Ditutup pada hari Ahad. Anda boleh WhatsApp bila-bila masa dan kami akan balas dalam waktu bekerja.'],
      ['Apa yang perlu saya hantar untuk masalah aircond?', 'Gambar unit dalaman dan labelnya (jenama dan model), apa yang berlaku (tak sejuk, menitis, bising), berapa unit, dan anggaran bila kali terakhir diservis.'],
      ['Bekalan elektrik asyik trip. Apa patut saya buat?', 'Jika ada bau terbakar, percikan api atau asap, tutup suis utama di kotak DB, jauhkan diri dan telefon. Untuk trip atau sebahagian bekalan terputus, WhatsApp gambar kotak DB dan beritahu apa yang sedang dihidupkan semasa ia trip.'],
    ],
  },
  contact: {
    eyebrow: 'Hubungi',
    title: 'Beritahu kami apa yang perlu dibaiki.',
    sub: 'Cara paling cepat ialah WhatsApp bersama beberapa gambar. Panggilan dialu-alukan dalam waktu bekerja.',
    call: 'Telefon',
    whatsapp: 'WhatsApp',
    address: 'Alamat',
    hours: 'Waktu operasi',
    days: [['Isnin–Sabtu', '9 PG – 6 PTG'], ['Ahad', 'Ditutup']],
    today: 'Hari ini',
    maps: 'Buka di Google Maps',
    directions: 'Dapatkan arah',
    waMsg: 'Hai EY Creative Reno & Designs, saya ingin bertanya tentang satu kerja.',
  },
  footer: {
    tagline: 'Renovasi · Elektrik · Aircond · Reka bentuk dalaman',
    photos: 'Foto ialah imej stok ilustrasi (Unsplash), bukan projek EY.',
    toTop: 'Kembali ke atas',
    pitch: 'Konsep laman web disediakan untuk studio ini. Bukan laman rasmi lagi — sedia dijadikan milik anda.',
    pitchLink: 'Hubungi pereka',
    rights: 'Semua tanda dagangan milik pemiliknya.',
  },
}

export const content = { en, ms }
